### ISSUE TITLE
Flutter web build

### ISSUE THREAD

**Issue by loothood** [sourcecaster/connectme#1]
Hi,

Thank you for the project. It's very helpful.
I want to use it for WebSocket client-server communication in flutter project.
And here I faced the error:
when I'm trying to build it for the web:
`flutter run -d chrome` I get the error:
```
Running "flutter pub get" 
Launching lib/main.dart on Chrome in debug mode...
../../../.pub-cache/hosted/pub.dartlang.org/connectme-2.1.0/lib/connectme.dart:5:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
Waiting for connection from debug service on Chrome...             23.2s
Failed to compile application.
```
Could you help me, please? What I'm doing wrong?
Code:
`main.dart`
```
import 'package:connectme/connectme.dart';
import 'package:flutter/material.dart';

void main() async {
  await ConnectMe.connect('ws://127.0.0.1:31337');

  runApp(const MaterialApp());
}
```

**Comment by sourcecaster** [comment]
Unfortunately, there is no web support for dart:ffi which is used in connectme. Though you can check out connectme.js package here https://github.com/sourcecaster/connectme.js

**Comment by loothood** [comment]
Thank you for the answer.
Could you explain a bit more, please? Do you mean that I have to use javascript on the client side? I don't see any difference in the example folder in connectme and connectmejs repos:
https://github.com/sourcecaster/connectme/blob/main/example/example.dart
https://github.com/sourcecaster/connectme.js/blob/master/example/example.dart

**Comment by sourcecaster** [comment]
Example files are not updated in JS repository. That's why it's only on github and not npmjs.com. But the API is almost the same. With the exception that it's client only and, obviously, you can't use TCP sockets, only WebSockets.

I'll give you a quick example:

```javascript
let cm = require('connectme');
let pm = require('./generated/protocol.generated.mjs');

let client = new cm.ConnectMeClient(
    host, // websocket endpoint url
    [], // protocols - used in: new WebSocket(url, protocols)
    true, // auto reconnect (default true)
    30,  // query timeout (default 30)
    console.log, // onLog handler
    console.error, // onError handler
    handleConnect, // onConnect handler
    handleDisconnect // onDisconnect handler
);

client.register(pm.protocolMessageFactory);
await client.connect();

client.listen(pm.UpdatesMessage, (message) => {
    console.log(message.toString());
});

let response = await client.send(new pm.HelloRequest({name: 'Mr. Freeman'}));
console.log(response.toString());
```

In order to generate packme classes I usually add a file bin/compile.mjs which contains only 1 line:
```javascript
import 'packme/lib/compiler.mjs';
```

And then modify my package.json:
```json
"scripts": {
    "compile": "node bin/compile.mjs packme src/generated",
},
```

And you just npm run compile.

**Comment by loothood** [comment]
Thank you!
